name: rnaseq_alignment_environment
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.5.1
  - samtools=1.4
  - snakemake=3.11.0
  - pyyaml=3.11
  - hisat2=2.1.0
  - samtools=1.4
  - subread=1.5.2
